name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
    - uses: AnnikaCodes/install-ziglint@v0.1
    - run: npm install
    - run: npm run integration
