name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
    - uses: AnnikaCodes/install-ziglint@v0.1
    # TODO: remove once install-ziglint is fixed to properly place binary on the path
    - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
    - run: npm install
    - run: npm run integration
